name = "algomon"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "algomon"
database_id = "c946d250-48f2-4526-b6e1-b6e61fc86f7f"

[vars]
ENVIRONMENT = "production"
